feat: Adds tabs, tab content, period breakdown, wallet settings
NiceNode/nice-node pull request #139
Opened 2022-12-06 06:47 UTC by corn-potage

2022-12-06 23:27 UTC, jgresham commented
running `npm exec tsc` locally will show the errors occurring in ci/cd

2022-12-14 22:43 UTC, jgresham commented
@corn-potage when you get some time from the website, please take a look at the review comments above and let me know what you think :)

2022-12-15 06:01 UTC, jgresham requested changes

2022-12-20 22:51 UTC, corn-potage commented on src/renderer/Generics/redesign/Tabs/Tabs.tsx
> +  children: React.ReactElement<TabsProps>[];
seems like it was `React.ReactElement<TabsProps>[];` on an earlier commit, but it's now `children: React.ReactElement[];`

2023-01-24 02:36 UTC, jgresham approved these changes

2023-01-24 02:40 UTC, merged