fix: temporary modal states on add node flow
NiceNode/nice-node pull request #598
Opened 2024-06-09 02:00 UTC by corn-potage

- keeps user configured settings in a temporary object, allowing users to go back and forth from node settings
- resets temporary object only if user changes initial node package to something else

fixes #408

2024-06-12 20:00 UTC, jgresham requested changes
LGTM!

except e2e tests are failing add node after splash screen and I am getting a blank screen after selecting next when selecting "Ethereum node"

2024-06-14 15:53 UTC, corn-potage commented
@jgresham awesome to see that the issue got caught! I've fixed it, and it's now ready for review again 👍

2024-06-14 17:59 UTC, jgresham commented
> @jgresham awesome to see that the issue got caught! I've fixed it, and it's now ready for review again 👍

yeah! cool to see the test work and now passing!

2024-06-14 18:03 UTC, merged

2024-06-14 18:03 UTC, jgresham commented
awesome @corn-potage thank you!